# Generated by Django 5.1.6 on 2025-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_stock_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(null=True, related_name='stocks', through='logistic.StockProduct', to='logistic.product'),
        ),
    ]
